#!/bin/bash

echo "🚀 Water Polo Rankings API - Serverless Deployment Setup"
echo "========================================================="
echo ""
echo "1. First, create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: waterpolo-rankings-api-serverless"
echo "   - Description: Water Polo Rankings API - Serverless version for Vercel deployment"
echo "   - Set to Public (so Vercel can access it easily)"
echo "   - DO NOT initialize with README, .gitignore, or license (we already have these)"
echo "   - Click 'Create repository'"
echo ""
echo "2. After creating the repository, copy the repository URL and run:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/waterpolo-rankings-api-serverless.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Then deploy to Vercel:"
echo "   - Go to https://vercel.com/new"
echo "   - Import your new repository"
echo "   - Set Framework Preset: Other"
echo "   - Root Directory: leave as './' (root)"
echo "   - Build Command: leave empty"
echo "   - Install Command: pip install -r requirements.txt"
echo "   - Add Environment Variable: MONGO_URI = your MongoDB connection string"
echo "   - Click Deploy"
echo ""
echo "📁 Current repository status:"
git status
echo ""
echo "📊 Files ready for deployment:"
ls -la
